## Python 복습

### Markdown 수식 작성
    - LaTEX 태그로 작성 가능

$$
\begin{pmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
\end{pmatrix}
+
\begin{pmatrix}
5 & 5 & 5 \\
5 & 5 & 5 \\
\end{pmatrix}
$$

$$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{pmatrix}
\times
\begin{pmatrix}
5 & 5  \\
5 & 5  \\
5 & 5  \\
\end{pmatrix}
$$

$\begin{matrix}1&2\\3&4\\ \end{matrix}$
$\begin{pmatrix}1&2\\3&4\\ \end{pmatrix}$
$\begin{bmatrix}1&2\\3&4\\ \end{bmatrix}$
$\begin{Bmatrix}1&2\\3&4\\ \end{Bmatrix}$
$\begin{vmatrix}1&2\\3&4\\ \end{vmatrix}$
$\begin{Vmatrix}1&2\\3&4\\ \end{Vmatrix}$

$$
\begin{aligned}
f(x)&=ax^2+bx+c\\
g(x)&=Ax^4
\end{aligned}$$

### Numpy
    - 데이터는 행렬로 표현(영상도 포함)
    - 선형대수 / 통계 연산을 위한 라이브러리

    Pandas : 데이터 분석에 가장 많이 활용
    Numpy : 알고리즘 활용에 numpy가 필수적 패키지

In [2]:
# 호출
import numpy as np

#### array broadcasting
    - 차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것
    - 딥러닝에서 bias(편향) 계산을 할 때 주로 사용

In [4]:
ary = np.array(np.random.randint(10,100,10))
ary

array([69, 56, 52, 18, 27, 59, 82, 62, 99, 73])

In [10]:
# 초기 가중치 생성
ary = np.array(np.random.randn(10)) # 표준겅규분포를 따르는 난수 생성 -> 초기 가중치 생성 때 사용
ary

array([-1.36502805,  1.35991675,  0.23573603,  0.37960314,  0.07783435,
        0.40438409,  0.11809907,  0.92341999,  0.61365926,  0.57061858])

In [11]:
# 평향값 생성
bias = np.random.rand(1)
bias

array([0.97919491])

In [13]:
ary + bias  # array broadcasting

array([-0.38583314,  2.33911166,  1.21493094,  1.35879805,  1.05702926,
        1.383579  ,  1.09729398,  1.9026149 ,  1.59285417,  1.54981349])

### 통계함수
    - max, min, mean, median, var, std

In [15]:
np.max(ary), np.min(ary) # min-max normailization 때 사용 -> 데이터 정규화

(1.3599167544078823, -1.365028049884608)

### Random 모듈
 - seed : 랜덤 모듈의 규칙값. 난수 생성 환경 고정
 - randint : 균등분포로 정수 랜덤
 - randn : 정규분포로 난수 생성
 - shuffle : 무작위 섞기
 - choice : 특정확률로 데이터 뽑기

### seed

In [16]:
seed = 603 # 머신러닝,딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1 = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)

In [17]:
r1, r2, r3

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

머신러닝 예시
scaling 처리 후 return 값으로 ndarray 타입 데이터로 출력

In [18]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

X = np.random.randint(1,100,10).reshape(-1,2) # 5행 2열
df = pd.DataFrame(X)
df




0   1
0  94  21
1  49  93
2   5  96
3  29  83
4  77  45

In [19]:
scaled_data = MinMaxScaler().fit_transform(df)
scaled_data, type(scaled_data)

(array([[1.        , 0.        ],
        [0.49438202, 0.96      ],
        [0.        , 1.        ],
        [0.26966292, 0.82666667],
        [0.80898876, 0.32      ]]),
 numpy.ndarray)

In [20]:
zero_ary = np.zeros((4,4))
zero_ary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
import numpy as np
w = np.random.randn(4)
shp = np.zeros((4,4))

sum = 0
for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i == j: shp[i][j] = w[i]

shp
        
        

array([[ 1.81284992,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.35103089,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.41353508,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.68993506]])

In [47]:
import numpy as np
diag_matrix = np.diag(np.random.randn(4))

diag_matrix

array([[ 0.18165408,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.12496912,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.14189891,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.71035095]])

### Function
- 반복성을 줄이고 함수로 선언한 연산을 재사용
- 객체 지향 언어의 가장 큰 장점

In [51]:
'''python
def 함수명(파라미터):
return 출력값
'''

'python\ndef 함수명(파라미터):\nreturn 출력값\n'

In [55]:
# 리턴을 선언하지 않고 사용하는 경우 > 함수가 연산 도구로만 사용될 때
# 전역변수, 지역변수
num = 603
print(num)

def today():
    global num
    
    num = 604
    print(num)

today()

print(num)
 


603
604
604


### map 함수와 pandas apply는 유사한 기능
- 순서가 있는 데이터값에 함수를 모두 적용하여 결과를출력하는 함수

'''python
map(적용할 함수, 입력할 데이터)
'''

In [56]:
num_txt = "1 2 3 4 5 6"
num_int = list(map(int, num_txt.split(' ')))
num_int

[1, 2, 3, 4, 5, 6]

#### lambda 함수
- 간단한 연산을 구현하여 일시적으로 사용하는 함수

'''python
lanbda 리턴:연산
'''


In [58]:
seq = np.random.randint(1,101,10)
print(seq)
q = list(map(lambda x:x//3,seq))
print(q)

[ 12  68  54  14  47  23  76 100  35  71]
[4, 22, 18, 4, 15, 7, 25, 33, 11, 23]
