In [1]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier      # 분류
# from sklearn.neighbors import KNeighborsRegressor       # 회귀 예측
from sklearn.linear_model import LinearRegression       # 선형 회귀
from sklearn.preprocessing import PolynomialFeatures    # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import requests
import random
import glob,os.path,re
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = 10
matplotlib.rcParams['axes.unicode_minus']=False

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/rickiepark/hongong-ml/master/perch_full.csv')
perch = df.to_numpy()
perch

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32],
       [18.7 ,  5.2 ,  3.12],
       [19.  ,  5.64,  3.05],
       [19.6 ,  5.14,  3.04],
       [20.  ,  5.08,  2.77],
       [21.  ,  5.69,  3.56],
       [21.  ,  5.92,  3.31],
       [21.  ,  5.69,  3.67],
       [21.3 ,  6.38,  3.53],
       [22.  ,  6.11,  3.41],
       [22.  ,  5.64,  3.52],
       [22.  ,  6.11,  3.52],
       [22.  ,  5.88,  3.52],
       [22.  ,  5.52,  4.  ],
       [22.5 ,  5.86,  3.62],
       [22.5 ,  6.79,  3.62],
       [22.7 ,  5.95,  3.63],
       [23.  ,  5.22,  3.63],
       [23.5 ,  6.28,  3.72],
       [24.  ,  7.29,  3.72],
       [24.  ,  6.38,  3.82],
       [24.6 ,  6.73,  4.17],
       [25.  ,  6.44,  3.68],
       [25.6 ,  6.56,  4.24],
       [26.5 ,  7.17,  4.14],
       [27.3 ,  8.32,  5.14],
       [27.5 ,  7.17,  4.34],
       [27.5 ,  7.05,  4.34],
       [27

In [3]:
# 타겟
perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0,
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0,
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0,
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0,
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0,
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0,
     1000.0, 1000.0]
     )

In [12]:
train_input, test_input, train_target, test_target = train_test_split(perch,perch_weight,random_state=42)
train_input

array([[19.6 ,  5.14,  3.04],
       [22.  ,  5.88,  3.52],
       [18.7 ,  5.2 ,  3.12],
       [17.4 ,  4.59,  2.94],
       [36.  , 10.61,  6.74],
       [25.  ,  6.44,  3.68],
       [40.  , 11.93,  7.11],
       [39.  , 12.43,  7.35],
       [43.  , 11.93,  7.28],
       [22.  ,  5.64,  3.52],
       [20.  ,  5.08,  2.77],
       [22.  ,  6.11,  3.52],
       [24.  ,  7.29,  3.72],
       [27.5 ,  7.17,  4.34],
       [43.  , 12.51,  7.42],
       [40.  , 11.73,  7.22],
       [24.  ,  6.38,  3.82],
       [21.  ,  5.92,  3.31],
       [27.5 ,  7.05,  4.34],
       [40.  , 12.38,  7.46],
       [32.8 , 10.03,  6.02],
       [26.5 ,  7.17,  4.14],
       [36.5 , 10.88,  6.86],
       [13.7 ,  3.53,  2.  ],
       [22.7 ,  5.95,  3.63],
       [15.  ,  3.82,  2.43],
       [37.  , 10.57,  6.37],
       [35.  , 11.49,  7.8 ],
       [28.7 ,  7.59,  4.64],
       [23.5 ,  6.28,  3.72],
       [39.  , 11.14,  6.  ],
       [21.  ,  5.69,  3.56],
       [23.  ,  5.22,  3.63],
       [22

In [13]:
lr = LinearRegression()
lr.fit(train_input,train_target)
lr.predict(test_input)


array([-322.78309496,   52.96101903,  329.77783424,  171.46884473,
        149.65836217,  789.639144  ,  383.68482432,  250.05247716,
        813.2470793 ,  126.13660027,  980.20626415,  -33.35965799,
        357.76466578,  421.8675313 ])

In [14]:
print(lr.score(train_input,train_target))
print(lr.score(test_input,test_target))

0.9559326821885706
0.8796419177546367


In [18]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures()
poly.fit(train_input)
train_input

train_poly = poly.transform(train_input)
train_poly

array([[1.000000e+00, 1.960000e+01, 5.140000e+00, 3.040000e+00,
        3.841600e+02, 1.007440e+02, 5.958400e+01, 2.641960e+01,
        1.562560e+01, 9.241600e+00],
       [1.000000e+00, 2.200000e+01, 5.880000e+00, 3.520000e+00,
        4.840000e+02, 1.293600e+02, 7.744000e+01, 3.457440e+01,
        2.069760e+01, 1.239040e+01],
       [1.000000e+00, 1.870000e+01, 5.200000e+00, 3.120000e+00,
        3.496900e+02, 9.724000e+01, 5.834400e+01, 2.704000e+01,
        1.622400e+01, 9.734400e+00],
       [1.000000e+00, 1.740000e+01, 4.590000e+00, 2.940000e+00,
        3.027600e+02, 7.986600e+01, 5.115600e+01, 2.106810e+01,
        1.349460e+01, 8.643600e+00],
       [1.000000e+00, 3.600000e+01, 1.061000e+01, 6.740000e+00,
        1.296000e+03, 3.819600e+02, 2.426400e+02, 1.125721e+02,
        7.151140e+01, 4.542760e+01],
       [1.000000e+00, 2.500000e+01, 6.440000e+00, 3.680000e+00,
        6.250000e+02, 1.610000e+02, 9.200000e+01, 4.147360e+01,
        2.369920e+01, 1.354240e+01],
       [1.