In [1]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier # 분류
# from sklearn.neighbors import KNeighborsRegressor  # 회귀-예측
from sklearn.linear_model import LinearRegression  # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [2]:
#[ 도미 ]
bream_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 31.5, 32.0, 32.0, 32.0, 33.0, 33.0,
33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0]
bream_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 500.0, 340.0, 600.0, 600.0, 700.0, 700.0,
610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0]
#[ 빙어 ]
smelt_length = [9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
smelt_weight = [6.7, 7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [34]:
# 로지스틱 회귀로 도미, 빙어 test세트의 5개를 분류하고
# 5개르 몇 %의 확률로 선택을 햇는지 출력하시오.
# train,test 정답률을 출력하시오.
fish = [0 for i in range(35)]+[1 for j in range(14)] 
length = bream_length + smelt_length
weight = bream_weight + smelt_weight

a = [weight,length,fish]
df = pd.DataFrame(a)
df=df.T
df.shape

datas = [ [l,w,r] for l,w,r in zip(length,weight,fish)]

# fish_input = np.array(df.iloc[:,:2])
# fish_target = np.array(df.iloc[:,2])
# fish_input

In [55]:
# train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target,random_state=2)
# len(test_input)
# random.shuffle(datas)
# np.array(datas)
idx = [i for i in range(49)]
random.shuffle(idx)
train_input = [datas[i][0:2] for i in idx[:44]]
test_input = [datas[i][0:2] for i in idx[44:]]
train_target = [datas[i][2] for i in idx[:44]]
test_target = [datas[i][2] for i in idx[44:]]
train_input
test_input
test_target
# idx

[24,
 47,
 35,
 46,
 11,
 43,
 1,
 39,
 30,
 21,
 9,
 37,
 12,
 42,
 13,
 31,
 40,
 4,
 28,
 10,
 17,
 3,
 38,
 25,
 26,
 18,
 16,
 44,
 36,
 7,
 48,
 15,
 22,
 41,
 8,
 34,
 14,
 45,
 32,
 27,
 29,
 33,
 5,
 23,
 0,
 20,
 6,
 19,
 2]

In [48]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [49]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_scaled,train_target)
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

1.0
1.0


In [51]:
lr.classes_

array([0, 1])

In [50]:
# 5개를 몇 %의 확률로 선택을 햇는지 출력하시오.
# train,test 정답률을 출력하시오.
proba = lr.predict_proba(test_scaled[:5])
np.round(proba,decimals=3)

array([[0.939, 0.061],
       [0.086, 0.914],
       [0.964, 0.036],
       [0.111, 0.889],
       [0.154, 0.846]])

In [52]:
lr.predict(test_scaled)

array([0, 1, 0, 1, 1])

In [53]:
# 길이 25, 무게 150
lr.predict([[25,150]])

array([0])

In [3]:
lr.predict([[5,10]])

NameError: name 'lr' is not defined